version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source dependencies...
      - npm install
  pre_build:
    commands:
      - echo Creating .env file from AWS Environment Variables...
      - echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL}" >> .env
      - echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}" >> .env
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
